import { Inter } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import SocialMedia from "./components/socialMedia/SocialMedia";
import "./globals.css";

// Load Google Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vault Development App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`} suppressHydrationWarning>
        <SocialMedia />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
